name: Lint and Publish
on: push
jobs:
  packages:
    name: packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
  lint:
    name: lint
    needs: packages
    runs-on: ubuntu-latest
    steps:
      - run: npm lint

  publish:
    name: publish
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: JS-DevTools/npm-publish@v1
        with:
          registry: https://npm.pkg.github.com
          token: ${{ secrets.GITHUB_TOKEN }}
